version: '3.8'
services:
  server:
    image: node:12.18.4
    volumes:
      - /mnt/d/Users/Desktop/学习代码/node服务端/egg/1-helloworld:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    ports:
      - 7001:7001
    command: npm run start
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - /mnt/d/Users/Desktop/leave/data:/var/lib/mongodb/data
